server:
  port: 8080
  http2:
    enabled: true

spring:
  application:
    name: ai-hypertext
  main:
    web-application-type: reactive
  webflux:
    base-path: /
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:-1}
      max-request-size: ${MAX_REQUEST_SIZE:-1}
      enabled: true
  jackson:
    default-property-inclusion: non_null
  http:
    codecs:
      max-in-memory-size: 64MB

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

app:
  ollama:
    model: "qwen3:8b"
